#!/bin/sh

set -eu

# Requirements:
#
# awscli
# ayusin >= 0.3.0 (optional)
# gum
# restic >= 0.16.0
# resticprofile >= 0.23.0
# yq

version='1.0.1'
me="${0##*/}"
share_dir="${0%/*}/../share/pagpapanatili"

. "${share_dir}/shared.subr"

usage() {
	echo "Usage: $me [options] [command]"
	echo "       $me [options] [resticprofile flags] [profile name.]restic-command [restic flags]"
	echo "       $me [options] [resticprofile flags] [profile name.]resticprofile-command [command specific flags]"
	echo
	echo '       --version               Show version'
	echo '       -v, --verbose           Enable verbose output'
	echo '       -n, --dry-run           Show what would have happened'
	echo '       -h, --help              Show this help'
	echo '       --help-resticprofile    Show the help for resticprofile'
	echo '       --help-restic           Show the help for restic'
	echo
	echo '       config, configure       Configure'
	echo '       aws                     Wrapper for awscli (sets profile/region)'
	echo '       version                 Show version'
	exit
}

usage_resticprofile() {
	run_command exec resticprofile --help
}

usage_restic() {
	run_command exec restic --help
}

while [ $# -ne 0 ]; do
	case "$1" in
		--version|version)
			echo "$me $version"
			maybe_run_command resticprofile version
			maybe_run_command restic version
			exit 0
			;;
		-v|--verbose)
			opt_verbose=1
			shift
			;;
		-n|--dry-run)
			opt_dryrun=1
			shift
			;;
		-h|--help)
			usage
			;;
		--help-resticprofile)
			usage_resticprofile
			;;
		--help-restic)
			usage_restic
			;;
		config|configure)
			. "${share_dir}/configure.subr"
			configure
			;;
		aws)
			. "${share_dir}/configure.subr"
			. "${share_dir}/aws.subr"

			shift
			aws_wrapper "$@"
			;;
		*)
			break
			;;
	esac

	setup_options
done

PAGPAPANATILI_PWD="$PWD"
export PAGPAPANATILI_PWD

cd "$share_dir"

exec_resticprofile "$@"
