{{ $user_config_dir := or .Env.PAGPAPANATILI_USER_CONFIG_DIR (print .Env.HOME "/.pagpapanatili") -}}
---
# yaml-language-server: $schema=https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

version: "1"

includes:
  - "profiles.d/*.yaml"
  - "{{ $user_config_dir }}/profiles.d/*.yaml"
