#!/bin/sh

set -eu

test "${PAGPAPANATILI_VERBOSE:-0}" -eq 1 && set -x

rc=0
restic "$@" || rc=$?

if [ "${PROFILE_COMMAND:-}" = 'backup' ] && [ $rc -eq 3 ]; then
	gum log --level=warn --time=datetime 'Some source files could not be read (incomplete snapshot)'
	exit 0
fi

exit $rc
