#!/bin/sh
#
# This file is maintained by pag(1). It may be replaced during configure.
#

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='Backup home directory'

task_start

$DRYRUN pag home.backup

task_end
