#!/bin/sh
#
# Warning: This file is managed by pag(1) and will be overwritten during a
# configure operation
#

# shellcheck disable=SC1090
. "$(ayusin --common)"
# shellcheck disable=SC2034
task_description='Backup home directory'

task_start

$DRYRUN pag home.backup || task_fail

task_end
